/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_api_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_api_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Workspace */
        get: operations["project_workspace_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Models */
        get: operations["get_models_api_admin_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/model-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Options */
        get: operations["get_model_options_api_admin_model_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Artifact */
        Artifact: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Revision Id */
            revision_id: string;
            /** Component Id */
            component_id: string | null;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "step" | "glb" | "plot";
            /** Bytes */
            bytes: number;
            /** Storage Path */
            storage_path: string;
        };
        /** CalculationCheck */
        CalculationCheck: {
            /** Name */
            name: string;
            /** Passed */
            passed: boolean;
            /** Detail */
            detail: string;
        };
        /** CalculationRecord */
        CalculationRecord: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Run Id */
            run_id: string;
            /** Revision Id */
            revision_id: string | null;
            result: components["schemas"]["CalculationResult"];
            /** Stale */
            stale: boolean;
            /** Reproducible */
            reproducible: boolean;
            /** Created At */
            created_at: string;
        };
        /** CalculationResult */
        CalculationResult: {
            /** Title */
            title: string;
            /** Inputs */
            inputs: {
                [key: string]: components["schemas"]["Quantity"];
            };
            /** Assumptions */
            assumptions: string[];
            /** Equations */
            equations: string[];
            /** Results */
            results: {
                [key: string]: components["schemas"]["Quantity"];
            };
            /** Checks */
            checks: components["schemas"]["CalculationCheck"][];
            /** Conclusion */
            conclusion: string;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /** Created At */
            created_at: string;
        };
        /** Component */
        Component: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Source */
            source: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "solid" | "surface" | "assembly";
            /** Dependencies */
            dependencies: string[];
            /** Parameters */
            parameters: {
                [key: string]: number | string | boolean | number[] | number[][];
            };
            /**
             * Color
             * @default #b9c4ad
             */
            color: string;
            /** @default null */
            material: components["schemas"]["MaterialSpec"] | null;
        };
        /** ConfigurationFrame */
        ConfigurationFrame: {
            /** Instanceid */
            instanceId: string;
            frame: components["schemas"]["Frame"];
        };
        /** ConfigurationSpec */
        ConfigurationSpec: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Frames */
            frames: components["schemas"]["ConfigurationFrame"][];
            /**
             * Description
             * @default
             */
            description: string;
        };
        /**
         * FeatureOperation
         * @description Auditable modeling intent emitted by generated source.
         */
        FeatureOperation: {
            /** Id */
            id: string;
            /** Componentid */
            componentId: string;
            /** Operation */
            operation: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** Frame */
        Frame: {
            /** Position */
            position: [
                number,
                number,
                number
            ];
            /** Rotation */
            rotation: [
                number,
                number,
                number
            ];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Instance */
        Instance: {
            /** Id */
            id: string;
            /** Definitionid */
            definitionId: string;
            /**
             * Parentid
             * @default null
             */
            parentId: string | null;
            /** Name */
            name: string;
            frame: components["schemas"]["Frame"];
        };
        /**
         * JointSpec
         * @description Relationship between semantic references.
         *
         *     Joint kinds are intentionally extensible (for example rigid, revolute,
         *     cylindrical, gear, contact or a future specialist relation).
         */
        JointSpec: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Referencea */
            referenceA: string;
            /** Referenceb */
            referenceB: string;
            /**
             * Lowerlimit
             * @default null
             */
            lowerLimit: number | null;
            /**
             * Upperlimit
             * @default null
             */
            upperLimit: number | null;
            /**
             * Unit
             * @default
             */
            unit: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** Manifest */
        Manifest: {
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
            /**
             * Units
             * @default mm
             * @constant
             */
            units: "mm";
            /** Components */
            components: components["schemas"]["Component"][];
            /** Instances */
            instances: components["schemas"]["Instance"][];
            /**
             * Rootcomponentid
             * @default null
             */
            rootComponentId: string | null;
            /** References */
            references: components["schemas"]["SemanticReference"][];
            /** Joints */
            joints: components["schemas"]["JointSpec"][];
            /** Configurations */
            configurations: components["schemas"]["ConfigurationSpec"][];
            /** Featureoperations */
            featureOperations: components["schemas"]["FeatureOperation"][];
        };
        /**
         * MaterialSpec
         * @description Optional physical properties attached to a CAD definition.
         */
        MaterialSpec: {
            /** Name */
            name: string;
            /**
             * Densitykgm3
             * @default null
             */
            densityKgM3: number | null;
        };
        /** ModelConfigView */
        ModelConfigView: {
            /**
             * Role
             * @enum {string}
             */
            role: "coordinator" | "cad" | "engineering";
            /** Provider */
            provider?: string;
            /** Base Url */
            base_url?: string | null;
            /** Model Id */
            model_id: string;
            /** Max Output Tokens */
            max_output_tokens?: number | null;
            /** Key Hint */
            key_hint: string;
            /** Active */
            active: boolean;
            /** Version */
            version: number;
            /** Tested At */
            tested_at: string | null;
        };
        /** ModelOption */
        ModelOption: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Contextlength */
            contextLength: number;
        };
        /** ModelOptions */
        ModelOptions: {
            /** Freeonly */
            freeOnly: boolean;
            /** Syntheticnemotrontesting */
            syntheticNemotronTesting: boolean;
            /** Models */
            models: components["schemas"]["ModelOption"][];
        };
        /** Profile */
        Profile: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "engineer";
            /** Active */
            active: boolean;
            /** Must Change Password */
            must_change_password: boolean;
        };
        /** Project */
        Project: {
            /** Id */
            id: string;
            /** Owner Id */
            owner_id: string;
            /** Name */
            name: string;
            /** Current Revision Id */
            current_revision_id: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** Quantity */
        Quantity: {
            /** Value */
            value: number;
            /** Unit */
            unit: string;
        };
        /** RequirementCheck */
        RequirementCheck: {
            /** Id */
            id: string;
            /** Description */
            description: string;
            /** Kind */
            kind: string;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "failed" | "unverified";
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
        };
        /** Revision */
        Revision: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Run Id */
            run_id: string;
            /** Ordinal */
            ordinal: number;
            /** Summary */
            summary: string;
            manifest: components["schemas"]["Manifest"];
            /** Created At */
            created_at: string;
            /** Restored From */
            restored_from: string | null;
            /** @default null */
            validation: components["schemas"]["ValidationReport"] | null;
        };
        /** Run */
        Run: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Owner Id */
            owner_id: string;
            /** Base Revision Id */
            base_revision_id: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "waiting_input" | "paused" | "succeeded" | "failed" | "cancelled";
            /** Message */
            message: string;
            /** Selected Ids */
            selected_ids: string[];
            /** Error */
            error: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Workflow Id */
            workflow_id: string | null;
            /** Model Calls */
            model_calls: number;
            /** Backend Version */
            backend_version: number;
            /** Execution Environment */
            execution_environment: string;
        };
        /** RunEvent */
        RunEvent: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "status" | "tool" | "validation" | "error";
            /** Message */
            message: string;
            /** Created At */
            created_at: string;
            /**
             * Stage
             * @default null
             */
            stage: string | null;
            /**
             * Attempt
             * @default null
             */
            attempt: number | null;
            /**
             * Elapsed Ms
             * @default null
             */
            elapsed_ms: number | null;
        };
        /**
         * SemanticReference
         * @description Stable, code-authored geometry reference in component-local coordinates.
         *
         *     ``kind`` deliberately remains an open string.  The CAD agent may introduce
         *     domain-specific references without waiting for a backend enum migration.
         */
        SemanticReference: {
            /** Id */
            id: string;
            /** Componentid */
            componentId: string;
            /** Kind */
            kind: string;
            /**
             * Origin
             * @default null
             */
            origin: [
                number,
                number,
                number
            ] | null;
            /**
             * Direction
             * @default null
             */
            direction: [
                number,
                number,
                number
            ] | null;
            /**
             * Radiusmm
             * @default null
             */
            radiusMm: number | null;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** SessionView */
        SessionView: {
            /** Configured */
            configured: boolean;
            profile: components["schemas"]["Profile"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationReport */
        ValidationReport: {
            /** Identity */
            identity: {
                [key: string]: string;
            };
            /** Requirements */
            requirements: components["schemas"]["RequirementCheck"][];
            /** Allrequirementsverified */
            allRequirementsVerified: boolean;
            /** Inspection */
            inspection?: {
                [key: string]: unknown;
            };
            /** Review */
            review?: {
                [key: string]: unknown;
            };
        };
        /** WorkspaceState */
        WorkspaceState: {
            project: components["schemas"]["Project"];
            /** Revisions */
            revisions: components["schemas"]["Revision"][];
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /** Runs */
            runs: components["schemas"]["Run"][];
            /** Artifacts */
            artifacts: components["schemas"]["Artifact"][];
            /** Calculations */
            calculations: components["schemas"]["CalculationRecord"][];
            /** Events */
            events: components["schemas"]["RunEvent"][];
        };
        /** AppSettings */
        AppSettings: {
            /**
             * Emergencystop
             * @default false
             */
            emergencyStop: boolean;
            /**
             * Engineeringenabled
             * @default true
             */
            engineeringEnabled: boolean;
            /**
             * Surfacingenabled
             * @default true
             */
            surfacingEnabled: boolean;
            limits: components["schemas"]["Limits"];
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Baserevisionid */
            baseRevisionId: string | null;
            /** Selectedids */
            selectedIds: string[];
            /**
             * Idempotencykey
             * Format: uuid
             */
            idempotencyKey: string;
        };
        /** Limits */
        Limits: {
            /**
             * Maxmodelcalls
             * @default 24
             */
            maxModelCalls: number;
            /**
             * Maxrepairs
             * @default 2
             */
            maxRepairs: number;
            /**
             * Commandtimeoutseconds
             * @default 180
             */
            commandTimeoutSeconds: number;
            /**
             * Maxartifactbytes
             * @default 41943040
             */
            maxArtifactBytes: number;
            /**
             * Retainedexports
             * @default 5
             */
            retainedExports: number;
            /**
             * Monthlysandboxseconds
             * @default 7200
             */
            monthlySandboxSeconds: number;
            /**
             * Storagebudgetbytes
             * @default 800000000
             */
            storageBudgetBytes: number;
        };
        /** Snapshot */
        Snapshot: {
            manifest: components["schemas"]["Manifest"];
            /** Files */
            files: {
                [key: string]: string;
            };
        };
        /** FrontendContracts */
        FrontendContracts: {
            workspace: components["schemas"]["WorkspaceState"];
            session: components["schemas"]["SessionView"];
            settings: components["schemas"]["AppSettings"];
            models: components["schemas"]["ModelOptions"];
            model_config_view: components["schemas"]["ModelConfigView"];
            snapshot: components["schemas"]["Snapshot"];
            request: components["schemas"]["ChatRequest"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    session_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
        };
    };
    events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    project_workspace_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_models_api_admin_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigView"][];
                };
            };
        };
    };
    get_model_options_api_admin_model_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOptions"];
                };
            };
        };
    };
}
